### PR TITLE
Updating dockerfile to support use on kubernetes deployment

### PR DESCRIPTION
**Pull request by fleupold**
Adding inotifytools so that we can watch the filesystem for changes and tini so that we are not running as PID 1

### Test plan

Deployed as fleupold/dex_visualization_tools on Dockerhub and used in our deployment

### CODE REVIEW

**Comment by josojo** [comment]
Looks good.

But can you please update the readme:
If I am running a fresh build, I get:
```
docker run -it -v ~/gnosis/dex-visualization-tools/:/app/ order_book_printer

tini (tini version 0.18.0 - git.fec3683)
Usage: tini [OPTIONS] PROGRAM -- [ARGS] | --version

Execute a program under the supervision of a valid init process (tini)

Command line options:

  --version: Show version and exit.
  -h: Show this help message and exit.
  -s: Register as a process subreaper (requires Linux >= 3.4).
  -p SIGNAL: Trigger SIGNAL when parent dies, e.g. "-p SIGKILL".
  -v: Generate more verbose output. Repeat up to 3 times.
  -w: Print a warning when processes are getting reaped.
  -g: Send signals to the child's process group.
  -e EXIT_CODE: Remap EXIT_CODE (from 0 to 255) to 0.
  -l: Show license and exit.

```

**Comment by fleupold** [comment]
I readded bash as the default command so the existing tutorial should work.

**Review by josojo — APPROVED** [review]
This is a much better fix then adjusting the Readme. 

Thanks for cleaning the docker file so much!

**Comment by fleupold** [comment]
Adding inotifytools so that we can watch the filesystem for changes and tini so that we are not running as PID 1

### Test plan

Deployed as fleupold/dex_visualization_tools on Dockerhub and used in our deployment

**Pull request merged**
