### PR TITLE
[HotFix] Handle node_weights.values() == None

### PR DESCRIPTION
**Pull request by bh2smith**
We were experiencing the following error in log syncing process.

```
New result file: results/2020-06-13/instance_5306919_2020-06-13T19:22:03.268155309+00:00/06_solution_int_valid.json
...
Traceback (most recent call last):
  File "plot_solution_graph.py", line 228, in <module>
    output_dir)
  File "plot_solution_graph.py", line 112, in generate_plot
    **kwargs)
  File "/app/plot_utils.py", line 99, in plot_network
    cmax=max(node_weights.values()),
ValueError: max() arg is an empty sequence
```

This quick fix is by no means meant to be permanent, but perhaps we could use this PR to make a better decision on how to handle this case.

### CODE REVIEW

**Comment by josojo** [comment]
Thanks for finding a solution. Can you elaborate on why these weights can be empty in the first place?

**Comment by bh2smith** [comment]
> Thanks for finding a solution. Can you elaborate on why these weights can be empty in the first place?

At this point I cannot, but I presume this is exactly what we have been experiencing as an error on the open solver over the weekend. I could look closer at the code to determine what these `node_weights` actually are, but I imagine someone who wrote the code might know immediately.

Otherwise, I will take a look into this tomorrow.

**Comment by bh2smith** [comment]
Answer: `node_weights.values() == None` exactly when there are no `nodes` is an empty List.

I believe the relevant code here shows that the original contributor was expecting that it could be empty, but did not handle the case in the particular line of code we see changed in this PR. We see the definition of node_weights here, followed by an if block that does a few things when node_weights is non-empty.

https://github.com/gnosis/dex-visualization-tools/blob/bb9dbf8a5573e49b89587e8323dcd156ed6f87f4/plot_utils.py#L61-L73

Note that when `node_weights` is empty `node_weights.values()` is None.

The fishiest looking thing here is the re-definition of `node_weights` in the first line.

```py
node_weights = {nID: node_weights[nID] if nID in node_weights else wmin for nID in nodes}
```

Which says:

I want the same dictionary I had before, but I would like to extend the keys to include all the node ids from nodes (rather than just the original keys contained in node_weights) and when I come across a node that doesn't already have a value assigned to it use the minimum weight.

So, then the only way this could be empty is if `nodes` was empty which we will have to assume is the case.


and so the investigation continues...

**Comment by bh2smith** [comment]
In this scenario, nodes corresponds to `tokens` which must have been empty. I find this surprising because none of the other solvers were crapping out here. At first, I would think that the solver in question `dev-dfusion-open-solver-mainnet-master` has a token orderbook filter that might result in a Null token set, but further examination of the configuration shows no orderbook filter.



OK. So, It seems that the open-solver it attempting to plot trivial solutions. See, for example:

http://gnosis-dev-dfusion.s3-website.eu-central-1.amazonaws.com/#data/mainnet_dev/open-solver/results/2020-06-14/instance_5307145_2020-06-14T14:12:03.662271854+00:00/

**Comment by bh2smith** [comment]
It looks like the plot for a trivial solution in the standard solver differs here because it always contains OWL. See 

http://gnosis-dev-dfusion.s3-website.eu-central-1.amazonaws.com/#data/mainnet_dev/standard-solver/results/2020-06-14/instance_5306980_2020-06-14T00:25:32.496808319+00:00/

**Comment by bh2smith** [comment]
**Normal Trivial Solution Plot**

Screenshot 2020-06-14 at 4 34 32 PM

**Open Solver Trivial Solution Plot**

Screenshot 2020-06-14 at 4 34 44 PM

**Comment by bh2smith** [comment]
There appears to be this script `/script/sync-data.sh` that is somehow responsible for calling the plot generation, but I am not able to find it yet... Still digging.

**Comment by bh2smith** [comment]
I see now. The open solver is submitting an "prices" list in solution (attached) while the standard (and other solvers) always at least provide a price for OWL. 

Standard Solver Solution for Batch 5307072
[06_solution_int_valid.standard.json.txt](https://github.com/gnosis/dex-visualization-tools/files/4776940/06_solution_int_valid.standard.json.txt)

Open Solver Solution for Batch 5307072
[06_solution_int_valid.open.json.txt](https://github.com/gnosis/dex-visualization-tools/files/4776939/06_solution_int_valid.open.json.txt)


I would propose then that both, we enforce all solutions have a price for OWL (i.e. fix the Open solver here) but also that this project be capable of handling this case.

In fact, we probably shouldn't even be creating the html file if there is nothing to plot.


We could easily avoid this entire scenario with something like 

```py
    if not node_weights:
        return
```

but I would argue it would be a bit cleaner to detect if there are no nodes before even calling into plot function.

**Comment by josojo** [comment]
I also just investigated this a little bit and it seems like my newest configmap scripts are not working as intended ( or even more likely, we are still running with the old config maps).

Usually, this case should have been prevented  due to the non-plot function for trivial solutions
```
while read path action file; do
        if [[ "$file" == "06_solution_int_valid.json" ]]; then
          echo "New result file: ${path}${file}"
          isOrderVecEmpty=$(grep -ce "\"orders\":\s*\[\s*\]" "${path}${file}")
          # Only plot and store the solution if the order vector is not empty
          if [[ $isOrderVecEmpty -eq 0 ]]; then
            python plot_solution_graph.py ${path}${file} --logging warning
```

**Comment by fleupold** [comment]
@josojo `kubectl describe configmap dev-dfusion` shows you the script that is being used (it is the one you were expecting).


> In fact, we probably shouldn't even be creating the html file if there is nothing to plot.

@bh2smith We want to avoid plotting empty solution to make it easier to find instances that have meaningful data to show (on AWS all items in the results/ folder have non-trivial solutions)

**Comment by nlordell** [comment]
I think this PR should be merged regardless, as the plotting script shouldn't crash on an empty result file. To me, not generating these plots for trivial solutions is a separate issue (that should also be fixed).

**Comment by nlordell** [comment]
I'm also OK with empty solutions generating empty graphs (since it is my expectation that empty input will yield empty output).

**Review by nlordell — APPROVED** [review]

**Review by josojo — APPROVED** [review]
Yeah, upon rethinking I agree with you guys.

Thanks for digging into this issue Ben. I know this is a lot of work, especially on the weekend 👍

**Comment by nlordell** [comment]
Should we merge this? Especially since we are going to start using this in staging and potentially eventually production.

**Pull request merged**
